---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,	message = FALSE,	warning = FALSE, options(width = 120), fig.width = 12, fig.height = 8
)
```

# 메모리 정리
```{r}
rm(list=ls())
```

# 데이터 읽어 오기
```{r}
data(iris)
```

# EDA
```{r}
str(iris)
```
```{r}
summary(iris)
```
```{r}
rbind(head(iris,3), tail(iris,3))
```

```{r}
colSums(is.na(iris))
```

# 데이터 전처리
```{r}
# Species를 종별로 변수 생성 (one hot encoding)
iris.nn <- cbind(iris, model.matrix(~ 0 + Species, iris))
head(iris.nn, 3)
```

```{r}
# 훈련/검정 데이터 분리
idx <- sample(nrow(iris.nn), nrow(iris.nn)*0.75, replace = F)
iris.train <- iris.nn[idx, ]
iris.test <- iris.nn[-idx, ]
```

# 모델링
```{r}
# install.packages("neuralnet")
library(neuralnet)

# formula
model.formula <- as.formula(
  paste(paste(colnames(iris.train[,c(6:8)]), collapse = "+"), "~", paste(colnames(iris.train[,c(1:4)]), collapse = "+"))
)
model.nn <- neuralnet(model.formula, data = iris.train, hidden = c(10,10), rep = 5, err.fct = "ce",
                      linear.output = F, lifesign = "minimal", stepmax = 100000, threshold = 0.001)
```
```{r}
plot(model.nn, rep="best")
```

# 성과분석
```{r}
predict.nn <- compute(model.nn, iris.test[1:4])
idx <- apply(predict.nn$net.result, MARGIN = 1, which.max)
predicted <- c("setosa", "versicolor", "virginica")[idx]
```

```{r}
library(caret)
confusionMatrix(as.factor(predicted), iris.test$Species)
```
```{r}
library(pROC)
model.roc <- multiclass.roc(as.numeric(as.factor(predicted)), as.numeric(iris.test$Species))
plot.roc(model.roc$rocs[[1]], col="red", print.auc = T, print.auc.adj = c(0,-1), max.auc.polygon = T)
plot.roc(model.roc$rocs[[2]], col="green", print.auc = T, print.auc.adj = c(0,-2.5), add = T)
plot.roc(model.roc$rocs[[3]], col="blue", print.auc = T, print.auc.adj = c(0,-4.0), add = T)
legend("bottom", legend = c("setosa-versicolor", "setosa-virginica", "versicolor-virginica"), col = c("red", "green", "blue"), lwd=1)
```

