---
title: "nnet - R"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

# 메모리 초기화
```{r}
rm(list=ls())
```

# 데이터 읽어 오기
```{r}
data(iris)
```

# EDA
```{r}
str(iris)
```

```{r}
summary(iris)
```

```{r}
rbind(head(iris,3), tail(iris,3))
```

```{r}
colSums(is.na(iris))
```

# 데이터 전처리
```{r}
library(nnet)

# 종속변수가 multiclass로 one hot encoding 실행
species.ind <- class.ind(iris$Species)
species.ind[c(1,51,101), ]
```

```{r}
# 생성된 변수 추가
iris.nn <- cbind(iris, species.ind)
rbind(head(iris.nn,3), tail(iris.nn,3))
```

# 모델링
```{r}
# 훈련:검정 데이터 분리 (7:)
idx <- sample(nrow(iris.nn), nrow(iris.nn)*0.7, replace = F)
iris.train <- iris.nn[idx, ]
iris.test <- iris.nn[-idx, ]
head(iris.train)
```

```{r}
model.nn <- nnet(x = iris.train[, c(1:4)], y = iris.train[, c(6:8)], size = 10, softmax = T)
```

# 성능평가
```{r}
iris.pred <- predict(model.nn, iris.test[, c(1:4)], type="class")
library(caret)
confusionMatrix(as.factor(iris.pred), iris.test[, c(5)])
```
# 시각화 & 인사이트
```{r}
library(reshape2)
library("devtools")
source_url('https://gist.githubusercontent.com/fawda123/7471137/raw/466c1474d0a505ff044412703516c34f1a4684a5/nnet_plot_update.r')
plot.nnet(model.nn)
```
# 성능 튜닝
```{r}
# hidden layer node 수에 따른 성능 확인
set.seed(0982)
idx <- sample(nrow(iris.nn), nrow(iris.nn)*0.7, replace = F)
iris.train <- iris.nn[idx, ]
iris.test <- iris.nn[-idx, ]

results <- c()
for (nHL in 1:10) {
  model.nn <- nnet(x = iris.train[, c(1:4)], y = iris.train[, c(6:8)], size = nHL, softmax = T)
  iris.pred <- predict(model.nn, iris.test[, c(1:4)], type="class")
  cM <- confusionMatrix(as.factor(iris.pred), iris.test[, c(5)])
  results <- cbind(results, cM$overall[1])
}
cat(paste("Num.Node: ",  which.max(results), "\nAccuracy: ", max(results), sep = ""))
```

